// <auto-generated />
using System;
using BlackIce.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlackIce.Server.Data.Migrations
{
    [DbContext(typeof(BlackIceDbContext))]
    partial class BlackIceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("BlackIce.Server.Data.Account", b =>
                {
                    b.Property<string>("SteamId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.HasKey("SteamId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("BlackIce.Server.Data.Profile", b =>
                {
                    b.Property<string>("SteamId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PlaytimeSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("SteamId");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("BlackIce.Server.Data.Realm", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HackDifficultyIncrease")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Motd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Pvp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.ToTable("Realms");
                });

            modelBuilder.Entity("BlackIce.Server.Data.ServerState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BootstrapClaimed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BootstrapCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Motd")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ServerState");
                });

            modelBuilder.Entity("BlackIce.Server.Data.Profile", b =>
                {
                    b.HasOne("BlackIce.Server.Data.Account", null)
                        .WithOne("Profile")
                        .HasForeignKey("BlackIce.Server.Data.Profile", "SteamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlackIce.Server.Data.Account", b =>
                {
                    b.Navigation("Profile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
